// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZVfDHtiVjxqkUaXdR0ip7Fz6nbHXbNAc',
    appId: '1:413848784849:web:e30e89f3c98dada32e1af0',
    messagingSenderId: '413848784849',
    projectId: 'student-registration-632e7',
    authDomain: 'student-registration-632e7.firebaseapp.com',
    storageBucket: 'student-registration-632e7.firebasestorage.app',
    measurementId: 'G-B7FJX7CE3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPiCavK4xCKLtZJUNUp-r61hefrX337EY',
    appId: '1:413848784849:android:690948aef17e5ad22e1af0',
    messagingSenderId: '413848784849',
    projectId: 'student-registration-632e7',
    storageBucket: 'student-registration-632e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgScAC6QOBltbTAWnpRt_5WYULFG1sSk',
    appId: '1:413848784849:ios:9d2e2e92cb6f760f2e1af0',
    messagingSenderId: '413848784849',
    projectId: 'student-registration-632e7',
    storageBucket: 'student-registration-632e7.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgScAC6QOBltbTAWnpRt_5WYULFG1sSk',
    appId: '1:413848784849:ios:9d2e2e92cb6f760f2e1af0',
    messagingSenderId: '413848784849',
    projectId: 'student-registration-632e7',
    storageBucket: 'student-registration-632e7.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZVfDHtiVjxqkUaXdR0ip7Fz6nbHXbNAc',
    appId: '1:413848784849:web:e56c92c2cf1e5e8f2e1af0',
    messagingSenderId: '413848784849',
    projectId: 'student-registration-632e7',
    authDomain: 'student-registration-632e7.firebaseapp.com',
    storageBucket: 'student-registration-632e7.firebasestorage.app',
    measurementId: 'G-W0TKL3954Q',
  );
}
