// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkpPa1_27SSfvn5aR9YQjmRenwnQDnL90',
    appId: '1:1082578177401:web:138b2e8f6106fe59fab3a8',
    messagingSenderId: '1082578177401',
    projectId: 'student-app-a6142',
    authDomain: 'student-app-a6142.firebaseapp.com',
    storageBucket: 'student-app-a6142.firebasestorage.app',
    measurementId: 'G-7QRZB90NEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCorcH8gcPHnWgmh8qSD8_kz2_jD2xYCws',
    appId: '1:1082578177401:android:2f45527339e92eaefab3a8',
    messagingSenderId: '1082578177401',
    projectId: 'student-app-a6142',
    storageBucket: 'student-app-a6142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1dTFXuxgQCi4aSxy3SN1DpvwE9s_5joU',
    appId: '1:1082578177401:ios:4de1019a4a0c8d60fab3a8',
    messagingSenderId: '1082578177401',
    projectId: 'student-app-a6142',
    storageBucket: 'student-app-a6142.firebasestorage.app',
    iosBundleId: 'com.example.ex12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1dTFXuxgQCi4aSxy3SN1DpvwE9s_5joU',
    appId: '1:1082578177401:ios:4de1019a4a0c8d60fab3a8',
    messagingSenderId: '1082578177401',
    projectId: 'student-app-a6142',
    storageBucket: 'student-app-a6142.firebasestorage.app',
    iosBundleId: 'com.example.ex12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkpPa1_27SSfvn5aR9YQjmRenwnQDnL90',
    appId: '1:1082578177401:web:409bed0c235e193afab3a8',
    messagingSenderId: '1082578177401',
    projectId: 'student-app-a6142',
    authDomain: 'student-app-a6142.firebaseapp.com',
    storageBucket: 'student-app-a6142.firebasestorage.app',
    measurementId: 'G-CHB3CGG419',
  );
}
